config/routes.rb
Rails.application.routes.draw do
  root 'tickets#index'
  get "/404" => "errors#not_found"
  get "/500" => "errors#exception"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  namespace :api do
    devise_for :users
  end  
  
  resources :tickets
  post 'tickets/:id/mark_close' => 'tickets#mark_close', as: :close_ticket
  post 'tickets/:id/reopen' => 'tickets#reopen', as: :reopen_ticket

  resources :comments

  resources :members
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :owner, class_name: "User"

  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: {minimum: 1, maximum: 255}

  before_save :updates_for_owner

  attr_accessor :status_str

  STATUS = {
    open: 0,
    reopened: 1,
    assigned: 2,
    closed: 3
  }

  def status_str
    @status_str = Ticket::STATUS.keys[status.to_i]
  end

  private
    def updates_for_owner
      if self.owner_id.present?
        owner = User.find(self.owner_id)
        unless ['support_agent', 'admin'].include?(owner.role)
          self.owner_id = nil
        end
      end
    end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate!
  before_action :authenticate_admin!, only: [:destroy]
  before_action :set_ticket, only: [:show, :edit, :update, :destroy, :mark_close, :reopen]

  # GET /tickets
  # GET /tickets.json
  def index
    if params[:closed_in_last_month].present?
      @start_date = 30.days.ago
      @tickets = Ticket.where(status: 0).where("updated_at > #{@start_date.to_date}")
    else  
      @tickets = Ticket.all
    end
    respond_to do |format|
      format.html
      format.json
      format.pdf do
        pdf = TicketsPdf.new(@tickets, @start_date)
        send_data pdf.render, filename: "tickets.pdf", disposition: 'inline'
      end
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user = current_user if current_user

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render json: {id: @ticket.id, status: :created}, status: :created }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render json: {status: :ok}, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # PUT /tickets/1/mark_close
  # PUT /tickets/1/mark_close.json
  def mark_close
    respond_to do |format|
      if @ticket.update({status: Ticket::STATUS[:closed]})
        format.html { redirect_to @ticket, notice: 'Ticket was successfully marked as close.' }
        format.json { render json: {status: :ok}, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tickets/1/reopen
  # PUT /tickets/1/reopen.json
  def reopen
    @ticket.status = Ticket::STATUS[:reopened]
    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully reopened.' }
        format.json { render json: {status: :ok}, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:title, :description, :owner_id)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_for(ticket) do |f| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <strong><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</strong>

      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="row actions">
    <%= f.submit 'create', class: "btn btn-default" %>
  </div>
<% end %>

app/views/tickets/comments.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments for Ticket #<%= @ticket.id %></h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path(ticket_id: @ticket.id) %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h1>Tickets</h1>

<%= link_to 'Ticket closed since last month', tickets_path(format: 'pdf', closed_in_last_month: true), 'data-no-turbolink' => true %>

<table class="table table-striped table-condensed table-responsive">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.title %></td>
        <td><%= ticket.description %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<div class="row"><h1>New Ticket</h1></div>

<%= render 'form', ticket: @ticket %>

<div class="row"><%= link_to 'Back', tickets_path %></div>

app/views/tickets/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @ticket.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ticket.description %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>